### PR TITLE
[bug] Keymanager was not shutting down cleanly

### PR DESCRIPTION
**Pull request by bwagnerr**
Manually reverted 4a090d6e

That commit attempted to remove the temporary file
on keymanager del, the problem is that you can't control
when del is executed, and sometimes, the references to
ca_bundle and os will be gone already, that meant it
would break most times, especially when shutting down (because
you can't control the order of disposal), so I reverted it.

### CODE REVIEW

**Comment by fbernitt** [comment]
Hey, just saw this PR on the IRC. Can you please not merge it for now? Will talk about this with @bwagnerr tomorrow.

**Comment by kalikaneko** [comment]
I see nobody's assigned to this, and no comment since the last from @fbernitt asking to put it on hold. Is this still a valid PR?

**Comment by giovaneliberato** [comment]
I did a commit and it end up on the same PR, sorry for that.

It fixes the requirements-latest references. The packages for u1db and dirspec were removed from pypi. Now we need to download it directly from canonical's launchpad.
Also, updates pixelated repositories references.

**Comment by kalikaneko** [comment]
I see different commits in the pr than the commit that originated this pr. is this still a valid PR?

**Comment by bwagnerr** [comment]
Closing this PR, this was stale and does not make sense anymore

**Pull request closed without merging**
