### PR TITLE
Setup streamline

### PR DESCRIPTION
**Pull request by bwagnerr**
Bringing it back from a branch now, so it won't get lost.

The development setup described on the readme is enough to run
the tests and develop the keymanager along with any other
leap libraries now, it supports both setuptools and pip as
means of setting up dependencies

### CODE REVIEW

**Comment by zaraG** [comment]
@bwagnerr @meskio should we add twisted in the requirements-latest as well?

**Comment by zaraG** [comment]
@bwagnerr @kalikaneko i guess this pr will can be closed as well?

**Comment by bwagnerr** [comment]
Yes, considering kaliy wants to have bigger changes and has a plan already, it doesn't make sense to keep this

**Comment by kalikaneko** [comment]
closing. keymanager is now a submodule of leap.bitmask, see https://github.com/leapcode/bitmask-dev

**Pull request closed without merging**
