### PR TITLE
[feat] adapt to new events api on common

### PR DESCRIPTION
**Pull request by ivanalejandro0**
**DO NOT MERGE YET**

These are the changes needed to use the new events api on `leap.common` waiting to be merged on https://github.com/leapcode/leap_pycommon/pull/95

- Related: #6359

### CODE REVIEW

**Comment by meskio** [comment]
The code looks good to me, but all the tests are broken:
```
$ trial test leap.keymanager
leap.keymanager.tests.test_keymanager
  KeyManagerCryptoTestCase
    test_keymanager_encrypt_key_not_found ... No handlers could be found for logger "leap.soledad.client.secrets"
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/home/meskio/dev/leap/leap_pycommon/src/leap/common/events/client.py", line 431, in run
    self._init_zmq()
  File "/home/meskio/dev/leap/leap_pycommon/src/leap/common/events/client.py", line 283, in _init_zmq
    self._sub = self._zmq_connect_sub()
  File "/home/meskio/dev/leap/leap_pycommon/src/leap/common/events/client.py", line 330, in _zmq_connect_sub
    stream = self._zmq_connect(zmq.SUB, self._reg_addr)
  File "/home/meskio/dev/leap/leap_pycommon/src/leap/common/events/client.py", line 306, in _zmq_connect
    server_public, _ = zmq.auth.load_certificate(server_public_file)
  File "/home/meskio/dev/leap/env/local/lib/python2.7/site-packages/zmq/auth/certs.py", line 87, in load_certificate
    raise IOError("Invalid certificate file: {0}".format(filename))
IOError: Invalid certificate file: /home/meskio/.config/leap/events/zmq_certificates/public_keys/server.key
```

I guess the problem is in https://github.com/leapcode/leap_pycommon/pull/95.

**Comment by ivanalejandro0** [comment]
> The code looks good to me, but all the tests are broken:

I just got
```
➜ trial test leap.keymanager

[... lots of output ...]

Ran 40 tests in 92.554s

PASSED (successes=40)
```

Please make sure that you have updated all the related branches to the latest commit, I've force-pulled the branches a couple of times during the last days.

**Comment by meskio** [comment]
Can it be that you had this `~/.config/leap/events/zmq_certificates/public_keys/server.key` pregenerated by running bitmask or something before? If I run bitmask before the tests I don't see this fialure, but if I `rm ~/.config/leap` and run the tests I get this error. I think the tests should work without need of any environment setted. We might need to do `event_server.ensure_server()` in the tests, or to pass a mocked event server.

I'm even wondering why is using the `~/.config` we change the home folder in the tests to don't mess up with your system.

**Comment by meskio** [comment]
https://github.com/andrejb/leap_pycommon/pull/1 fixes the test issues

**Pull request merged**
