### PR TITLE
port to new soledad async api

### PR DESCRIPTION
**Pull request by meskio**
**missing changes in leap.mail and maybe other to be compatible with the new API**

It needs to synchronize the merge with the soledad async API and the upgrades in leap.mail.

### CODE REVIEW

**Comment by meskio** [comment]
> is this already- reviewed? can we merge temporarily into the feature/async-api branch to test together with soledad/mail?

I think @andrejb wanted to give it a second review, but it's mostly finished the reviewing.

> @meskio: how does this branch relate with your branch meskio/feature/6240_signed_key2 ?

This branch contains more stuff that I did after I submited this pull-req. I'm waiting for this pull-req to be merged to submit a second pull-req with the new stuff that will be needed to test email.

**Comment by kalikaneko** [comment]
sooo... this could be merged into feature/async-api :)

**Comment by meskio** [comment]
I'm still waiting for @andrejb to give it a green light.

**Comment by meskio** [comment]
It's merged in https://github.com/leapcode/keymanager/tree/feature/async-api

**Pull request closed without merging**
